# Generated by Django 5.2.6 on 2025-09-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
