# Generated by Django 5.2.6 on 2025-09-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_driver_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cell_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
